spring.application.name=Auth
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=521452A3s

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true