name: Student API CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build application
        working-directory: ./StudentAPI
        run: mvn clean package

      - name: Show test reports
        if: failure()
        working-directory: ./StudentAPI
        run: |
          echo "===== Surefire Reports ====="
          find target/surefire-reports -type f -maxdepth 1 -print
          echo "===== Report Contents ====="
          cat target/surefire-reports/*.txt