- name: Build application
  working-directory: ./StudentAPI
  run: mvn clean package || true

- name: Show test reports
  working-directory: ./StudentAPI
  run: |
    echo "===== FILES ====="
    find target/surefire-reports -type f -print

    echo "===== XML REPORT ====="
    cat target/surefire-reports/*.xml

    echo "===== TEXT REPORT ====="
    cat target/surefire-reports/*.txt