- name: Build application
  working-directory: ./StudentAPI
  run: mvn clean package

- name: Show test reports
  if: failure()
  working-directory: ./StudentAPI
  run: |
    echo "===== Surefire Reports ====="
    find target/surefire-reports -type f -maxdepth 1 -print
    echo "===== Report Contents ====="
    cat target/surefire-reports/*.txt